* xDEVS

** Introduction

   This library includes a set of C++, JAVA and Python classes that provide an event-driven simulation interface. The interface also follows the formalism /Discrete Event System Specification (DEVS)/. The project final goal is to elaborate the fastest DEVS simulation interface with capacity to simulated models in virtual and real time, and to run simulations in sequential (single-threaded), parallel (multi-threaded) and distributed (not shared memory) architectures. Initial research in the xDEVS interface can be found in [[http://doi.org/10.1177/0037549717690447][Reconsidering the performance of DEVS modeling and simulation environments using the DEVStone benchmark]]. There are three main branches: c++, java and python, each one offering the equivalent simulation interface for each programming language.

** Top features

   - PDEVS Modeling and Simulation formalism
   - Object-Oriented Programming
   - Support for sequential, parallel and distributed (this last feature only in JAVA and Python, for now) architectures.
   - Good performance, compared to other simulation engines

** Quick start

   Switch to the corresponding branch. A README file will be found to start with minimal examples and demos.
